project_id = "xromfzhdjkhnukawxsjf"

[functions.join_room]
verify_jwt = false

[functions.nominate_player]
verify_jwt = false

[functions.place_bid]
verify_jwt = false

[functions.finalize_sale]
verify_jwt = false

[functions.add_ai_agents]
verify_jwt = false

[functions.ai_agent]
verify_jwt = false

[functions.start_auction]
verify_jwt = false